#!/bin/bash

wget "https://ftp.gnu.org/gnu/bash/bash-5.2.21.tar.gz" -P ${1}

cd ${1}

tar -xvf ${1}/bash-5.2.21.tar.gz -C ${1}
cd bash-5.2.21

./configure CFLAGS='-static' CXXFLAGS='-static' CC="i686-linux-gnu-gcc" --prefix="${2}"
make CFLAGS='-static' CXXFLAGS='-static' CC="i686-linux-gnu-gcc"
make install 