#!/bin/bash

wget "https://www.nano-editor.org/dist/v8/nano-8.0.tar.xz" -P ${1}

cd ${1}

tar -xvf ${1}/nano-8.0.tar.xz -C ${1}
cd nano-8.0

./configure CFLAGS='-static' CXXFLAGS='-static' CC="i686-linux-gnu-gcc" --prefix="${2}/bin"
make CFLAGS='-static' CXXFLAGS='-static' CC="i686-linux-gnu-gcc"
make install 