#!/bin/bash

wget "https://www.python.org/ftp/python/3.12.3/Python-3.12.3.tar.xz" -P ${1}

cd ${1}

tar -xvf ${1}/Python-3.12.3.tar.xz -C ${1}
cd Python-3.12.3

./configure LDFLAGS="-static" --disable-shared CC="i686-linux-gnu-gcc" CXX="i686-linux-gnu-g++" --prefix="${2}" --enable-optimizations
make LDFLAGS="-static" LINKFORSHARED=" " CC="i686-linux-gnu-gcc" CXX="i686-linux-gnu-g++" -j$(nproc)
make install 