name: Build BaseLinux ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script to build ISO
        run: |
          chmod +x bbuilder
          ./bbuilder

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v2
        with:
          name: BaseLinux ISO
          path: BaseLinux/BaseLinux.iso
